### ISSUE TITLE
Enhance the ui of password change of admins

### ISSUE THREAD

**Issue by atm1504** [atm1504/IITP-Mess#23]
Enhance the password change page ui of the admins.
File name is ```admin-chng-pass.php```

**Comment by shreyaswikriti** [comment]
I would like to work on this

**Comment by shreyaswikriti** [comment]
![password change (2)](https://user-images.githubusercontent.com/57635473/72205419-b429a680-34a8-11ea-81ee-f8c59db9a5e3.png)
